// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class gPlay
{
        public const string achievement_achievement10 = "CgkIgr6bkeMCEAIQCQ"; // <GPGSID>
        public const string achievement_achievement11 = "CgkIgr6bkeMCEAIQCg"; // <GPGSID>
        public const string achievement_achievement12 = "CgkIgr6bkeMCEAIQCw"; // <GPGSID>
        public const string achievement_achievement13 = "CgkIgr6bkeMCEAIQDA"; // <GPGSID>
        public const string achievement_achievement14 = "CgkIgr6bkeMCEAIQDQ"; // <GPGSID>
        public const string achievement_achievement01 = "CgkIgr6bkeMCEAIQAA"; // <GPGSID>
        public const string achievement_achievement02 = "CgkIgr6bkeMCEAIQAQ"; // <GPGSID>
        public const string achievement_achievement03 = "CgkIgr6bkeMCEAIQAg"; // <GPGSID>
        public const string achievement_achievement04 = "CgkIgr6bkeMCEAIQAw"; // <GPGSID>
        public const string achievement_achievement05 = "CgkIgr6bkeMCEAIQBA"; // <GPGSID>
        public const string achievement_achievement06 = "CgkIgr6bkeMCEAIQBQ"; // <GPGSID>
        public const string achievement_achievement07 = "CgkIgr6bkeMCEAIQBg"; // <GPGSID>
        public const string achievement_achievement08 = "CgkIgr6bkeMCEAIQBw"; // <GPGSID>
        public const string achievement_achievement09 = "CgkIgr6bkeMCEAIQCA"; // <GPGSID>
        public const string leaderboard_players_bests = "CgkIgr6bkeMCEAIQDg"; // <GPGSID>

}

